/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.eybsolution.islamic.buzz;

public final class R {
    public static final class anim {
        public static final int left_menu_left_to_right=0x7f040000;
    }
    public static final class animator {
        public static final int left_menu_slide_right=0x7f050000;
    }
    public static final class array {
        public static final int left_menu_titles=0x7f0a0000;
    }
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int border_color=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int border_width=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int corner_radius=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int dua_heading=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int dua_image=0x7f010001;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int dua_meaning=0x7f010003;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int dua_pronunciation=0x7f010002;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int is_oval=0x7f010008;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int round_background=0x7f010007;
    }
    public static final class color {
        public static final int action_bar_background=0x7f07000c;
        public static final int app_theme=0x7f070000;
        public static final int border=0x7f07000f;
        public static final int content_holder_background=0x7f07000b;
        public static final int dua_head_background=0x7f070004;
        public static final int dua_head_foreground=0x7f070003;
        public static final int dua_meaning_background=0x7f070008;
        public static final int dua_meaning_foreground=0x7f070007;
        public static final int dua_pronounce_background=0x7f070006;
        public static final int dua_pronounce_foreground=0x7f070005;
        public static final int grid_state_focused=0x7f07000e;
        public static final int grid_state_pressed=0x7f07000d;
        public static final int heading_bkg=0x7f070001;
        public static final int heading_umrah=0x7f070002;
        public static final int left_side_menu_item_background=0x7f07000a;
        public static final int menu_divider=0x7f070009;
    }
    public static final class dimen {
        public static final int about_heading_text_size=0x7f080016;
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f080000;
        public static final int activity_vertical_margin=0x7f080001;
        public static final int desc_bottom=0x7f080006;
        public static final int desc_left=0x7f080004;
        public static final int desc_right=0x7f080007;
        public static final int desc_top=0x7f080005;
        public static final int dua_container_margin_top=0x7f080012;
        public static final int dua_head_padding=0x7f08000d;
        public static final int dua_margin_left=0x7f08000b;
        public static final int dua_margin_right=0x7f08000c;
        public static final int dua_meaning_padding_bottom=0x7f08000f;
        public static final int dua_meaning_padding_left=0x7f080010;
        public static final int dua_meaning_padding_right=0x7f080011;
        public static final int dua_meaning_padding_top=0x7f08000e;
        public static final int dua_padding_bottom=0x7f08000a;
        public static final int dua_padding_left=0x7f080008;
        public static final int dua_padding_right=0x7f080009;
        public static final int heading_left=0x7f080002;
        public static final int heading_padding_right=0x7f080003;
        public static final int image_detail_pager_margin=0x7f080013;
        public static final int update_item_LCS_bottom=0x7f080014;
        public static final int update_item_LCS_up=0x7f080015;
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int app_icon=0x7f020001;
        public static final int app_icon_small=0x7f020002;
        public static final int app_logo=0x7f020003;
        public static final int besm_1=0x7f020004;
        public static final int comment=0x7f020005;
        public static final int comment_small=0x7f020006;
        public static final int default_user=0x7f020007;
        public static final int default_user_1=0x7f020008;
        public static final int divider=0x7f020009;
        public static final int dua_after_salatul_ihram=0x7f02000a;
        public static final int dua_after_tawafulwida=0x7f02000b;
        public static final int dua_allahummainni_zalamtunafsi=0x7f02000c;
        public static final int dua_at_safa=0x7f02000d;
        public static final int dua_at_safa_1=0x7f02000e;
        public static final int dua_at_safa_2=0x7f02000f;
        public static final int dua_before_slaughtering=0x7f020010;
        public static final int dua_between_safa_marwah_1=0x7f020011;
        public static final int dua_between_safa_marwah_2=0x7f020012;
        public static final int dua_bismillahi_allahu_akbar=0x7f020013;
        public static final int dua_enrout_to_arafat=0x7f020014;
        public static final int dua_for_halaq_or_qasr=0x7f020015;
        public static final int dua_on_entring_masjid_al_haram=0x7f020016;
        public static final int dua_on_sighting_kaba=0x7f020017;
        public static final int dua_outside_makkah=0x7f020018;
        public static final int dua_rabbana=0x7f020019;
        public static final int dua_seeing_kaba=0x7f02001a;
        public static final int dua_subhanallahi=0x7f02001b;
        public static final int dua_tawaful_wida=0x7f02001c;
        public static final int dua_to_muzdalifa=0x7f02001d;
        public static final int dua_ya_rabbal_baiti=0x7f02001e;
        public static final int empty_photo=0x7f02001f;
        public static final int hajj=0x7f020020;
        public static final int ic_launcher=0x7f020021;
        public static final int ic_menu=0x7f020022;
        public static final int info_update=0x7f020023;
        public static final int intention_hajj=0x7f020024;
        public static final int intention_hajj_cum_umrah=0x7f020025;
        public static final int kaba=0x7f020026;
        public static final int kalima_4_big=0x7f020027;
        public static final int kalima_4_small=0x7f020028;
        public static final int like=0x7f020029;
        public static final int like_small=0x7f02002a;
        public static final int photogrid_list_selector=0x7f02002b;
        public static final int ring_3=0x7f02002c;
        public static final int rounded=0x7f02002d;
        public static final int share=0x7f02002e;
        public static final int share_small=0x7f02002f;
        public static final int splash=0x7f020030;
        public static final int talbiyah=0x7f020031;
        public static final int transperent_color=0x7f020033;
        public static final int umrah_niyyat=0x7f020032;
    }
    public static final class id {
        public static final int action_settings=0x7f0d001c;
        public static final int clear_cache=0x7f0d001d;
        public static final int container=0x7f0d0001;
        public static final int content_holder=0x7f0d0005;
        public static final int contnet_window=0x7f0d0003;
        public static final int date_and_time=0x7f0d0018;
        public static final int ddd=0x7f0d0017;
        public static final int dua_heading=0x7f0d0006;
        public static final int dua_image=0x7f0d0007;
        public static final int dua_meaning=0x7f0d0009;
        public static final int dua_pronumciation=0x7f0d0008;
        public static final int gridView=0x7f0d000c;
        public static final int id_about_eybSolutionsLinkText=0x7f0d0000;
        public static final int imageView=0x7f0d000a;
        public static final int left_menu_handle=0x7f0d0004;
        public static final int left_side_menu=0x7f0d0002;
        public static final int location=0x7f0d0016;
        public static final int menu_icon=0x7f0d000f;
        public static final int menu_scroll_view=0x7f0d000d;
        public static final int menu_title=0x7f0d0010;
        public static final int pager=0x7f0d000b;
        public static final int pager_header=0x7f0d0012;
        public static final int posted_image=0x7f0d001a;
        public static final int scroll_view_container=0x7f0d000e;
        public static final int textView1=0x7f0d001b;
        public static final int textView2=0x7f0d0019;
        public static final int umrah_viewpager=0x7f0d0011;
        public static final int upates_holder=0x7f0d0013;
        public static final int user_image=0x7f0d0014;
        public static final int user_name=0x7f0d0015;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int activity_home=0x7f030001;
        public static final int content_window=0x7f030002;
        public static final int divider=0x7f030003;
        public static final int dua=0x7f030004;
        public static final int hajj_day_fifth=0x7f030005;
        public static final int hajj_day_four=0x7f030006;
        public static final int hajj_day_one=0x7f030007;
        public static final int hajj_day_six=0x7f030008;
        public static final int hajj_day_three=0x7f030009;
        public static final int hajj_day_two=0x7f03000a;
        public static final int hajj_intro=0x7f03000b;
        public static final int hajj_tawaful_wida=0x7f03000c;
        public static final int image_detail_fragment=0x7f03000d;
        public static final int image_detail_pager=0x7f03000e;
        public static final int image_grid_fragment=0x7f03000f;
        public static final int imram_dos_and_donts=0x7f030010;
        public static final int left_side_menu=0x7f030011;
        public static final int left_side_menu_item=0x7f030012;
        public static final int splash=0x7f030013;
        public static final int umrah=0x7f030014;
        public static final int umrah_halaq=0x7f030015;
        public static final int umrah_ihram=0x7f030016;
        public static final int umrah_intro=0x7f030017;
        public static final int umrah_prior_departure=0x7f030018;
        public static final int umrah_sai=0x7f030019;
        public static final int umrah_tawaf=0x7f03001a;
        public static final int updates=0x7f03001b;
        public static final int updates_item=0x7f03001c;
        public static final int ziyarah=0x7f03001d;
    }
    public static final class menu {
        public static final int home=0x7f0c0000;
        public static final int main_menu=0x7f0c0001;
    }
    public static final class string {
        public static final int about_this_version=0x7f090011;
        public static final int about_this_version_desc=0x7f090010;
        public static final int action_settings=0x7f090003;
        public static final int after_drinking_water=0x7f09009b;
        public static final int after_dua=0x7f0900cb;
        public static final int after_dua_make_istilam=0x7f09009c;
        public static final int after_halaq_all_requlations=0x7f090036;
        public static final int after_halaq_qasr_perform_the=0x7f090082;
        public static final int after_sunrise=0x7f090049;
        public static final int after_sunset_leave_for=0x7f090056;
        public static final int after_the_rami=0x7f090077;
        public static final int after_the_sacrifice=0x7f09007d;
        public static final int after_this_umrah=0x7f090032;
        public static final int app_name=0x7f090000;
        public static final int approach_the_small_shaytan=0x7f090092;
        public static final int clear_cache_complete_toast=0x7f09000a;
        public static final int clear_cache_menu=0x7f090009;
        public static final int collect_small_peasized_pebbles=0x7f09005d;
        public static final int comment=0x7f09000e;
        public static final int day_four_you_are=0x7f09008d;
        public static final int day_three_subhsadiq=0x7f090061;
        public static final int dua=0x7f090016;
        public static final int dua_after_niyyah=0x7f0900ae;
        public static final int dua_after_niyyah_meaning=0x7f0900b0;
        public static final int dua_after_niyyah_pronounce=0x7f0900af;
        public static final int dua_after_salatul_ihram_meaning=0x7f0900b2;
        public static final int dua_after_salatul_ihram_pronounce=0x7f0900b1;
        public static final int dua_after_tawafulwida=0x7f090028;
        public static final int dua_after_tawafulwida_meaning=0x7f09002a;
        public static final int dua_after_tawafulwida_pronounce=0x7f090029;
        public static final int dua_allahummainni_zalamtunafsi_meaning=0x7f090018;
        public static final int dua_allahummainni_zalamtunafsi_pronounce=0x7f090017;
        public static final int dua_at_arafat=0x7f09004f;
        public static final int dua_at_safa=0x7f0900f6;
        public static final int dua_at_safa_meaning=0x7f0900f8;
        public static final int dua_at_safa_pronounce=0x7f0900f7;
        public static final int dua_before_kissing_palm=0x7f0900db;
        public static final int dua_before_kissing_palm_meaning=0x7f0900dd;
        public static final int dua_before_kissing_palm_pronounce=0x7f0900dc;
        public static final int dua_before_slaughtering=0x7f09001e;
        public static final int dua_before_slaughtering_meaning=0x7f090020;
        public static final int dua_before_slaughtering_pronounce=0x7f09001f;
        public static final int dua_between_safa_marwah=0x7f0900f9;
        public static final int dua_between_safa_marwah_1_meaning=0x7f0900fb;
        public static final int dua_between_safa_marwah_1_pronounce=0x7f0900fa;
        public static final int dua_between_safa_marwah_2_meaning=0x7f0900fd;
        public static final int dua_between_safa_marwah_2_pronounce=0x7f0900fc;
        public static final int dua_bismillahi_allahu_akbar_meaning=0x7f09001d;
        public static final int dua_bismillahi_allahu_akbar_pronounce=0x7f09001c;
        public static final int dua_enrout_to_arafat=0x7f09004c;
        public static final int dua_enrout_to_arafat_meaning=0x7f09004e;
        public static final int dua_enrout_to_arafat_pronounce=0x7f09004d;
        public static final int dua_entering_masjid=0x7f0900c1;
        public static final int dua_entering_masjid_meaning=0x7f0900c3;
        public static final int dua_entering_masjid_pronounce=0x7f0900c2;
        public static final int dua_facin_hajarul_aswad_meaning=0x7f0900d8;
        public static final int dua_facin_hajarul_aswad_pronounce=0x7f0900d7;
        public static final int dua_facing_hajarul_aswad=0x7f0900d6;
        public static final int dua_for_halaq_or_qasr_meaning=0x7f090024;
        public static final int dua_for_halaq_or_qasr_pronounce=0x7f090023;
        public static final int dua_for_halaqa_or_qasr=0x7f090022;
        public static final int dua_intention_tawaf=0x7f0900d2;
        public static final int dua_intention_tawaf_meaning=0x7f0900d4;
        public static final int dua_intention_tawaf_pronounce=0x7f0900d3;
        public static final int dua_leaving_masjid=0x7f0900c4;
        public static final int dua_leaving_masjid_meaning=0x7f0900c6;
        public static final int dua_leaving_masjid_pronounce=0x7f0900c5;
        public static final int dua_on_sigting_heading=0x7f0900cc;
        public static final int dua_on_sigting_meaning=0x7f0900ce;
        public static final int dua_on_sigting_pronounce=0x7f0900cd;
        public static final int dua_outside_makkah=0x7f0900bc;
        public static final int dua_outside_makkah_meaning=0x7f0900be;
        public static final int dua_outside_makkah_pronounce=0x7f0900bd;
        public static final int dua_rabbana_atina=0x7f0900e2;
        public static final int dua_rabbana_atina_meaning=0x7f0900e4;
        public static final int dua_rabbana_atina_pronounce=0x7f0900e3;
        public static final int dua_seeing_kabah=0x7f0900c8;
        public static final int dua_seeing_kabah_meaning=0x7f0900ca;
        public static final int dua_seeing_kabah_pronounce=0x7f0900c9;
        public static final int dua_subhanallahi=0x7f0900e5;
        public static final int dua_subhanallahi_meaning=0x7f0900e7;
        public static final int dua_subhanallahi_pronounce=0x7f0900e6;
        public static final int dua_tawafulwida=0x7f090025;
        public static final int dua_tawafulwida_meaning=0x7f090027;
        public static final int dua_tawafulwida_pronounce=0x7f090026;
        public static final int dua_to_muzdalifa=0x7f090019;
        public static final int dua_to_muzdalifa_meaning=0x7f09001b;
        public static final int dua_to_muzdalifa_pronounce=0x7f09001a;
        public static final int dua_umrah_niyyat=0x7f0900aa;
        public static final int dua_while_slaughtering=0x7f090021;
        public static final int dua_while_stoning=0x7f090072;
        public static final int dua_ya_rabbal_baiti=0x7f0900e8;
        public static final int dua_ya_rabbal_baiti_meaning=0x7f0900ea;
        public static final int dua_ya_rabbal_baiti_pronounce=0x7f0900e9;
        public static final int enter_iharam_state=0x7f0900a8;
        public static final int exit_message=0x7f09000f;
        public static final int eybsolution=0x7f090013;
        public static final int fajr_salah_should=0x7f090062;
        public static final int farz_act_umrah=0x7f0900a0;
        public static final int farz_act_umrah_desc=0x7f0900a3;
        public static final int first_day_8th_dhul_hijjah=0x7f09003f;
        public static final int fourth_kalima_1=0x7f090014;
        public static final int fourth_kalima_2=0x7f090015;
        public static final int hajj_fifth_day=0x7f090093;
        public static final int hajj_fourth_day=0x7f09008c;
        public static final int hajj_ifrad=0x7f090037;
        public static final int hajj_qiraan=0x7f09002e;
        public static final int hajj_second_day=0x7f090047;
        public static final int hajj_sixth_day=0x7f090097;
        public static final int hajj_tamattu=0x7f090034;
        public static final int hajj_third_day=0x7f090060;
        public static final int halaq=0x7f090007;
        public static final int halaq_and_or_qasr=0x7f09007c;
        public static final int how_to_perform_rami=0x7f090070;
        public static final int if_after_tawaful_qudum=0x7f090083;
        public static final int if_you_are_performing=0x7f090041;
        public static final int ihraam=0x7f090005;
        /**  <string name="ihram_desc_1"><b>1</b>. Prior to entering the Miqat, try to perform Ghusl, otherwise Wudhu will suffice.Thereafter,wear the Ihraam,two white sheets, one for the upper and one for the lower part of the body. At this point, men may apply Itr (perfume). The women should keep all their body covered in their normal (Islamic) clothing, except the face.\n\n <b>2</b>. With the head covered Perform two Raka’at Nafl Salaah with the intention of ihraam. Recite Surah Al Kafirun in the first Raka’at and Surah Al Ikhlas in the second Raka’at, it is not necessary to read these particular verses, but traditions have recorded that the prophet (pbuh) had read them at this particular moment. <b>3</b>. On completing the two Raka’at, remove the headgear and make Niyyah of Umrah saying:</string> 
         */
        public static final int ihram_desc_1=0x7f0900a6;
        public static final int ihram_impermissible=0x7f0900b8;
        public static final int ihram_impermissible_text=0x7f0900b9;
        public static final int ihram_niyyah=0x7f0900a9;
        public static final int ihram_permissible=0x7f0900ba;
        public static final int ihram_permissible_text=0x7f0900bb;
        public static final int imageview_description=0x7f09000b;
        public static final int important=0x7f0900cf;
        public static final int important_if_performing_hajj=0x7f090066;
        public static final int important_it_is_thought=0x7f090096;
        public static final int important_note_one_must_try=0x7f09006f;
        public static final int important_rami_is_not_permissible=0x7f090091;
        public static final int important_tawafuzziyarah_is_a_fardh=0x7f090089;
        public static final int important_whoever_is_able_to_reach=0x7f090074;
        public static final int in_muzdalifa=0x7f09005a;
        public static final int in_no_place_available=0x7f0900ec;
        public static final int intention_hajj=0x7f09003d;
        public static final int intention_hajj_meaning=0x7f09003c;
        public static final int intention_hajj_pronounce=0x7f09003b;
        public static final int introduction=0x7f090004;
        public static final int istilam=0x7f0900d9;
        public static final int it_is_extremely=0x7f090055;
        public static final int it_is_not_permissible=0x7f090057;
        public static final int it_is_permissible=0x7f09005f;
        public static final int just_before_sunrise=0x7f090065;
        public static final int kalima_4_big_meaning=0x7f090053;
        public static final int kalima_4_big_pronounce=0x7f090052;
        public static final int kalima_4_small_meaning=0x7f090051;
        public static final int kalima_4_small_pronounce=0x7f090050;
        public static final int like=0x7f09000c;
        public static final int make_dual_after_salatul_Ihram=0x7f0900ad;
        public static final int masalah_after_umrah_one_must_not_shave=0x7f090031;
        public static final int masalah_if_one_choose_to_perform=0x7f090039;
        public static final int masalah_if_one_does_not_leave_mina=0x7f090095;
        public static final int masalah_if_one_has_completed_the_rites=0x7f09007f;
        public static final int masalah_if_one_returns_without_performing=0x7f09009d;
        public static final int masalah_if_performing_hajj_qiraan=0x7f090079;
        public static final int masalah_if_the_total=0x7f090045;
        public static final int masalah_it_is_an_act_of_bidah=0x7f09006b;
        public static final int masalah_it_is_desirable=0x7f090044;
        public static final int masalah_it_is_sunnah=0x7f09008b;
        public static final int masalah_it_is_wajib=0x7f090059;
        public static final int masalah_it_is_wajib_to_shave=0x7f09007e;
        public static final int masalah_sai_of_hajj=0x7f09003a;
        public static final int masalah_sai_of_hajj_which_is_normnally=0x7f090042;
        public static final int masalah_takbirat_of_tashriq=0x7f090046;
        public static final int masalah_tawaafuzziyarah_may_be_performed=0x7f090088;
        public static final int masalah_the_order_of_rami=0x7f09008f;
        public static final int masalah_the_rush_is_not=0x7f090075;
        public static final int masalah_this_sacrifice=0x7f090078;
        public static final int masalah_to_leave=0x7f09004a;
        public static final int masalah_to_perform_tawaafuzziyarah=0x7f090086;
        public static final int masalah_whilst_performing_rami=0x7f090073;
        public static final int masalah_women_infants_and_the_sick=0x7f09006e;
        public static final int masalah_wuquf_at_muzdalifa=0x7f090063;
        public static final int nahr=0x7f090076;
        public static final int nahr_is_not_wajib=0x7f090067;
        public static final int niyyah_making=0x7f0900a7;
        public static final int no_network_connection_toast=0x7f090008;
        public static final int note_it_is_better_for_women=0x7f090087;
        public static final int now_moving_towards_the_right=0x7f0900df;
        public static final int now_one_remains=0x7f090033;
        public static final int now_recite=0x7f0900b7;
        public static final int now_you_will_remain=0x7f09003e;
        public static final int offer_two_rakat_make_dua=0x7f09008a;
        public static final int on_completing_seventh_circuit=0x7f0900eb;
        public static final int on_seeing_kaba=0x7f0900c7;
        public static final int on_the_8th_dhulhijja=0x7f090040;
        public static final int on_this_day=0x7f09006a;
        public static final int one_must_wear=0x7f09002f;
        public static final int one_will_wear=0x7f090035;
        public static final int pebbles_for_defferent_days=0x7f09005e;
        public static final int pelting_only=0x7f090069;
        public static final int perform_maghrib_and_isha=0x7f09005b;
        public static final int place_both_palm=0x7f0900da;
        public static final int prior_to_departure=0x7f0900a4;
        public static final int prior_to_departure_desc=0x7f0900a5;
        public static final int proceed_to_black_line=0x7f0900d5;
        public static final int proceed_towards_the_well=0x7f0900ed;
        public static final int publisher=0x7f090012;
        public static final int rami_of_the_11th_and_12th=0x7f090090;
        public static final int rami_of_the_13th_dhul_hijjah=0x7f090098;
        public static final int rami_on_10th_can_be_performed=0x7f09006d;
        public static final int recite_durud=0x7f0900f2;
        public static final int reciting_talbiya_approach=0x7f090071;
        /**  ================================================ Sai ====================================================== 
         */
        public static final int sai=0x7f0900ee;
        public static final int sai_meaning=0x7f0900ef;
        public static final int sai_start_desc=0x7f0900f0;
        public static final int second_day_subah_sadiq=0x7f090048;
        public static final int share=0x7f09000d;
        public static final int talbiyah=0x7f0900b3;
        public static final int talbiyah_instr=0x7f0900b4;
        public static final int talbiyah_meaning=0x7f0900b6;
        public static final int talbiyah_pronounce=0x7f0900b5;
        public static final int tawaaf=0x7f090006;
        public static final int tawaf=0x7f0900d0;
        public static final int tawaf_adiya_desc=0x7f0900e1;
        public static final int tawaf_adiyah=0x7f0900e0;
        public static final int tawaf_intro=0x7f0900d1;
        public static final int tawaful_wida=0x7f090099;
        public static final int tawafulwida_my_be_performed=0x7f09009a;
        public static final int tawafuz_ziyarah=0x7f090081;
        public static final int tawafuzziyarah_can_be_performed=0x7f090085;
        public static final int the_duties_of=0x7f090068;
        public static final int the_only_action_to_be=0x7f09008e;
        public static final int the_procedures_of_this_day=0x7f090094;
        public static final int the_sacrifice_can_take=0x7f09007b;
        public static final int there_are_three=0x7f09002c;
        public static final int this_day=0x7f090043;
        public static final int this_is_known_as_istilam=0x7f0900de;
        public static final int to_muzdalifa=0x7f090058;
        public static final int to_remain_in_muzdalifa=0x7f09005c;
        public static final int try_to_remain=0x7f090064;
        public static final int types_of_hajj=0x7f09002b;
        public static final int types_of_hajj_desc=0x7f09002d;
        public static final int umrah=0x7f0900a1;
        public static final int umrah_first=0x7f09009e;
        public static final int umrah_niyyat=0x7f0900ab;
        public static final int umrah_niyyat_meaning=0x7f0900ac;
        public static final int upon_arrival=0x7f0900bf;
        public static final int upon_arrival_inst=0x7f0900c0;
        public static final int upon_arriving_in=0x7f090030;
        public static final int upon_completion_of_sai=0x7f0900f4;
        public static final int upon_shaving=0x7f0900f5;
        public static final int upon_the_time_of_zuhar=0x7f090054;
        public static final int version=0x7f090001;
        public static final int version_value=0x7f090002;
        public static final int virtues_of_umrah=0x7f09009f;
        public static final int virtues_of_umrah_desc=0x7f0900a2;
        public static final int when_to_perform_nahr=0x7f09007a;
        public static final int when_to_perform_rami=0x7f09006c;
        public static final int when_to_perform_tawafuzziyarah=0x7f090084;
        public static final int while_facing_kaba=0x7f0900f1;
        public static final int with_this_the_restriction_of_ihram=0x7f090080;
        public static final int wuquf_in_arafat=0x7f09004b;
        public static final int you_must_now_proceed=0x7f0900f3;
        public static final int you_will_enter_the_state_of_hajj=0x7f090038;
        public static final int ziyarah=0x7f0900fe;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f0b0000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f0b0002;
        public static final int AppTheme_FullScreen=0x7f0b0001;
        public static final int PhotoGridLayout=0x7f0b000a;
        public static final int dua_container=0x7f0b0005;
        public static final int dua_head=0x7f0b0007;
        public static final int dua_meaning=0x7f0b0009;
        public static final int dua_pronounce=0x7f0b0008;
        public static final int heading_text_style=0x7f0b0004;
        public static final int umrah_description=0x7f0b0006;
        public static final int umrah_heading=0x7f0b0003;
    }
    public static final class xml {
        public static final int config=0x7f060000;
    }
    public static final class styleable {
        /** Attributes that can be used with a RoundedImageView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RoundedImageView_android_scaleType android:scaleType}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundedImageView_border_color com.eybsolution.islamic.buzz:border_color}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundedImageView_border_width com.eybsolution.islamic.buzz:border_width}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundedImageView_corner_radius com.eybsolution.islamic.buzz:corner_radius}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundedImageView_is_oval com.eybsolution.islamic.buzz:is_oval}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundedImageView_round_background com.eybsolution.islamic.buzz:round_background}</code></td><td></td></tr>
           </table>
           @see #RoundedImageView_android_scaleType
           @see #RoundedImageView_border_color
           @see #RoundedImageView_border_width
           @see #RoundedImageView_corner_radius
           @see #RoundedImageView_is_oval
           @see #RoundedImageView_round_background
         */
        public static final int[] RoundedImageView = {
            0x0101011d, 0x7f010004, 0x7f010005, 0x7f010006,
            0x7f010007, 0x7f010008
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#scaleType}
          attribute's value can be found in the {@link #RoundedImageView} array.
          @attr name android:scaleType
        */
        public static final int RoundedImageView_android_scaleType = 0;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#border_color}
          attribute's value can be found in the {@link #RoundedImageView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:border_color
        */
        public static final int RoundedImageView_border_color = 3;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#border_width}
          attribute's value can be found in the {@link #RoundedImageView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:border_width
        */
        public static final int RoundedImageView_border_width = 2;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#corner_radius}
          attribute's value can be found in the {@link #RoundedImageView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:corner_radius
        */
        public static final int RoundedImageView_corner_radius = 1;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#is_oval}
          attribute's value can be found in the {@link #RoundedImageView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:is_oval
        */
        public static final int RoundedImageView_is_oval = 5;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#round_background}
          attribute's value can be found in the {@link #RoundedImageView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:round_background
        */
        public static final int RoundedImageView_round_background = 4;
        /** Attributes that can be used with a dua_styleable.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #dua_styleable_dua_heading com.eybsolution.islamic.buzz:dua_heading}</code></td><td></td></tr>
           <tr><td><code>{@link #dua_styleable_dua_image com.eybsolution.islamic.buzz:dua_image}</code></td><td></td></tr>
           <tr><td><code>{@link #dua_styleable_dua_meaning com.eybsolution.islamic.buzz:dua_meaning}</code></td><td></td></tr>
           <tr><td><code>{@link #dua_styleable_dua_pronunciation com.eybsolution.islamic.buzz:dua_pronunciation}</code></td><td></td></tr>
           </table>
           @see #dua_styleable_dua_heading
           @see #dua_styleable_dua_image
           @see #dua_styleable_dua_meaning
           @see #dua_styleable_dua_pronunciation
         */
        public static final int[] dua_styleable = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#dua_heading}
          attribute's value can be found in the {@link #dua_styleable} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:dua_heading
        */
        public static final int dua_styleable_dua_heading = 0;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#dua_image}
          attribute's value can be found in the {@link #dua_styleable} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.eybsolution.islamic.buzz:dua_image
        */
        public static final int dua_styleable_dua_image = 1;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#dua_meaning}
          attribute's value can be found in the {@link #dua_styleable} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:dua_meaning
        */
        public static final int dua_styleable_dua_meaning = 3;
        /**
          <p>This symbol is the offset where the {@link com.eybsolution.islamic.buzz.R.attr#dua_pronunciation}
          attribute's value can be found in the {@link #dua_styleable} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.eybsolution.islamic.buzz:dua_pronunciation
        */
        public static final int dua_styleable_dua_pronunciation = 2;
    };
}
